### ISSUE TITLE
Using objects as type for Output in CHECKSUM schema

### ISSUE THREAD

**Issue by utkarshgupta95** [ACCESS-NRI/schema#6]
Current the output property in checksum schema is a list of object each containing a checksum and a field.
```
checksum: '5227222155343350591'
  field: xt
- checksum: '5223776204015802370'
  field: xu
- checksum: '3524025294143080071'
  field: yt
- checksum: '3533356873625590408'
  field: yu
```
The problem is when comparing two checksum. Currently we iterating through output list of one checksum and performing a linear search on other checksum output list for each iteration. 

I suggest moving to an object
```
xt: '5227222155343350591'
yt: '3524025294143080071'
yu: '3533356873625590408'
```
This way we don't have to perform linear search for each iteration, instead it will be a constant time operation. It will also make the checksum file shorter and simpler.

**Comment by CodeGat** [comment]
So, it would go from something like:
```
output:
- checksum: '12345'
  field: xt
- checksum: '54321'
  field: xr
schema_version: 1-0-0
```
to:
```
output:
  xr: '54321'
  xt: '12345'
schema_version: 1-0-0
```
